apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app
  name: app
spec:
  volumes:
  - name: secret-volume
    emptyDir: {}
  containers:
  - image: busybox:1.36
    name: app
    resources: {}
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
