apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: exercise-14

labels:
  - pairs:
      env: staging

replicas:
- name: app1
  count: 3

# resources:
# - ../../base

# namespace: exercise-14

# #CommonLabels:
# #  env: staging

# Labels:
#   - pairs:
#       env: staging

# replicas:
# - name: app
#   count: 3

# # patches:
# #  path: replica_count.yaml